version: '3.9'

services:
  django:
    build:
      context: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    command: >
      sh -c " python manage.py migrate && gunicorn paymentchaser.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "4001:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
