# Generated by Django 5.2.1 on 2025-05-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="The customer's full name.", max_length=255, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, help_text='8 digit telephone number like Tigo or Claro numbers (e.g., 9900-9950)', max_length=8, null=True, verbose_name='Phone Number')),
                ('identity_card_number', models.CharField(help_text='Honduran identity card number (e.g., 0801-1999-00001) but like without hyphens', max_length=13, unique=True, verbose_name='Number of Identity Card')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['full_name'],
            },
        ),
    ]
