# Generated by Django 5.2.1 on 2025-05-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified',
            field=models.BooleanField(default=False, help_text="Indicates whether the customer's identity has been verified.", verbose_name='Verified'),
        ),
    ]
